sudo: false
language: node_js
node_js:
  - "8"
  - "lts/*"
  - "node"
scripts:
  - npm install codecov -g
after_success:
  - codecov

jobs:
  include:
    - stage: deploy
      node_js:
        - "node"
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: doc/
        github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        fqdn: tempo-client.leifgehrmann.com
        project_name: tempo-client
        on:
          branch: master
      before_deploy:
        - npm run doc
        - touch doc/.nojekyll
        - sed -i '/doc/d' .gitignore
