name: GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: npm install, build, and generate documentation
      run: |
        npm ci
        npm run build --if-present
        npm run doc
        touch ./doc/.nojekyll
        sed -i '/doc/d' .gitignore
        echo "tempo-client.leifgehrmann.com" >> ./doc/CNAME

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./doc
        force_orphan: true
