name: NPM Audit

on: 
  - schedule:
    - cron: '0 9 */1 * *'
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'
      - name: Build and run audit
        run: |
          npm install
          npm run build
          npm audit
