name: NPM Outdated

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  outdated:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'
      - name: Run npm outdated
        run: |
          npm outdated
